export const ADDFRIEND = "ADDFRIEND";
export const REMOVEFRIEND = "REMOVEFRIEND";
export const RECOMMEND = "RECOMMEND";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const REGISTER = "REGISTER";
export const RECENTLYRECOMMEND = "RECENTLYRECOMMEND";
export const UNRECENTLYRECOMMEND = "UNRECENTLYRECOMMEND";
